### ISSUE TITLE
Search in the app drawer is worse than the App Scope

### ISSUE THREAD

**Issue by kugiigi** [ubports/unity8#220]
## Device
Meizu MX4

## Description
Searching in the app scope is slow because the result gets displayed in a matter of seconds. Searching in the app drawer is faster in a way that the result is displayed almost instantly. Except that, it doesn't happen like that when there are many apps. Search processing isn't asynchronous so the UI lags in each letter typed which results to a horrible experience. 

I've tried edge on my daily driver phone which has many apps so I was able to experience this personally.

**Comment by lduboeuf** [comment]
For edge, did you tried recently to update ? I thought i've fixed that last week, see https://github.com/ubports/unity8/issues/212

**Comment by kugiigi** [comment]
Oh wow, that's cool to know. This is big. But the issue still exists on my Nexus5 and MX4.
I think my Nexus 5 has the update yesterday. My MX4 is now on stable again but I switched it to edge just 2 days ago I think.

**Comment by lduboeuf** [comment]
Oh then it is out of my skills, tested with 110 apps, search is still very fast

**Comment by kugiigi** [comment]
I would think that the fix did not land properly since it's still very slow on mine.

**Comment by UniversalSuperBox** [comment]
Sorry, the build failed because of Jenkins issues when that was merged. I've restarted the build: https://ci.ubports.com/blue/organizations/jenkins/ubports%2Funity8/detail/xenial_-_edge/61/pipeline

**Comment by lduboeuf** [comment]
I think you can close this issue since it is fixed in devel now

**Comment by kugiigi** [comment]
Yes, I upgraded my edge channel and it is now really fast there! Awesome job!
