### ISSUE TITLE
Unity8 session broken on bionic by latest mir updates

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/unity8#30]
_From @WebDrake on March 2, 2018 15:30_

The latest updates to bionic include an upgrade to mir 0.30.0.1.  This seems to break the ubports Unity8 desktop session: after typing the password to log in, nothing further happens (I seem to be stuck on lightdm).

Things obviously aren't 100% broken, since if I hit the power-off button on my laptop, the shutdown overlay appears (allowing me to choose between suspend, restart, and power-off), the Unity8 desktop fails to launch.

_Copied from original issue: ubports/unity8-desktop-install-tools#18_

**Comment by NeoTheThird** [comment]
_From @WebDrake on March 2, 2018 17:43_

Might be a more general upstream issue: https://bugs.launchpad.net/ubuntu/+source/libglvnd/+bug/1751414  I'll keep an eye on things there.

**Comment by nicman23** [comment]
the upstream issue is fixed (per launchpad devs)

but i still cannot start unity8 (fully up to date system)

**Comment by WebDrake** [comment]
Yup, same for me.  The link to the upstream issue was speculative, not certain.  So, could well be something else, then.

**Comment by WebDrake** [comment]
Looking in /var/log/lightdm/unity-sysytem-compositor.log.1.gz I notice the following:

```
/usr/sbin/unity-system-compositor: /usr/lib/x86_64-linux-gnu/libmirserver.so.47: version `MIR_SERVER_1.0' not found (required by /usr/sbin/unity-system-compositor)
```

Now, 2 further things:

* `libmirserver47` is supplied by `ubports`:

```
Package: libmirserver47
Version: 0.29.1+ubports1+0~20180228153016.2~1.gbpd786e9
Priority: optional
Section: libs
Source: mir
```

* the version of `libmirserver` introduced with mir v0.30.0.1 is `libmirserver46`:

```
Package: libmirserver46
Version: 0.30.0.1-0ubuntu2
Priority: optional
Section: libs
Source: mir
```

I'm curious at the version discrepancy (why `47` for ubports' package?), but this could also explain why Unity8 fails to start.

**Comment by WebDrake** [comment]
OK, further digging: I built a fresh `unity-system-compositor` package against the installed `libmirserver-dev` 0.30.0.1 package.  With this installed, USC starts correctly with lightdm, but Unity8 is still unable to launch.  However, the launch failure just dumps me straight back at the lightdm login screen (where I was able to log in successfully with another desktop).

Apport reports a crash of `/usr/bin/unity8` with `SIGABRT`, and looking at the stack trace I would guess that this is down to `qtmir` still depending on `libmirserver47` (ubports' package) instead of the upstream `libmirserver46` package.

So, I _think_ it should suffice to just also rebuild `qtmir-desktop` against the latest upstream `libmirserver-dev`, and install that, for things to work, as this is the only other mirserver-dependent package in ubports.

I'm trying to do this now myself, but running into difficulty with the qtmir build-dependencies; I'll report back if I succeed.

**Comment by WebDrake** [comment]
OK, I've succeeded in building and installing new qtmir packages that depend on the upstream `libmirserver`, but this did not improve matters further.

There's another upstream issue that looks likely to be related to this: https://github.com/MirServer/mir/issues/216

**Comment by nicman23** [comment]
from the issue you linked:

**Comment by nicman23** [comment]
from the issue you linked:

> Fixed in libglvnd 1.0.0-2ubuntu2

**Comment by mariogrip** [comment]
Mir does not seem to update there changelog file, so it was stuck on 0.29. Should be fixed with this: https://github.com/ubports/mir/commit/4e887ae4a6c2acbe099357d702d80ee7c8755bbb

I will also trigger rebuild for qtmir and usc

**Comment by WebDrake** [comment]
@mariogrip 
> Mir does not seem to update there changelog file, so it was stuck on 0.29. Should be fixed with this

Yea, I noticed this while trying to build upstream mir recently.  But I'd caution whether the changelog patch should be considered a fix or not: it suggests that there's something about how upstream is building their packages which is not reflected in how ubports does things.

That would probably be a more important/effective thing to investigate and fix, rather than carrying a workaround patch.  I'm going to try to chase up on this.

**Comment by WebDrake** [comment]
Unfortunately, updating to the new ubports packages doesn't fix things for me.  I haven't yet received the libglvnd 1.0.0-2ubuntu2 update, though, so I'll check and report back once that is in place.

**Comment by WebDrake** [comment]
Upgraded libglvnd0, and still unable to log in to Unity8.  Is this matched by other people's experience?

**Comment by WebDrake** [comment]
From Alan Griffiths on Telegram earlier today:

> I discovered this afternoon that the Mir-EGL patch mesa doesn't work with libglvnd. This breaks EGL clients using libmirclient and "nested" Mir. We (Mir) have decided to drop the patch from bionic rather that maintain even more that isn't strategic.
>
> That means more work for UBports but it is the same situation you'll face on other distros. It is a pain short-term but there's qtwayland for clients (in place of qtabuntuclient) and @mariogrip has done some work on a wayland platform for nesting (if still wanted on desktop).

**Comment by dobey** [comment]
Closing this as unity8 is working fine (well, as fine as unity8 works) with Mir 1.0 on bionic now.
